---

- name: "install Jenkins server" 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: "configure Helm repo"
    shell: |  
         helm repo add jenkinsci https://charts.jenkins.io |
         helm repo update
    
  - name: "Install Jenkins"
    shell: |
          helm install jenkins -n jumia jenkinsci/jenkins

  - name: "Retrieve Jenkins admin password"
    shell: |
          jsonpath="{.data.jenkins-admin-password}" |
          secret=$(kubectl get secret -n jumia jenkins -o jsonpath=$jsonpath) |
          echo $(echo $secret | base64 --decode)